### ISSUE TITLE
Truncate Archive

### ISSUE THREAD

**Issue by geckeon** [echothrust/echofish#23]
I tried to test Truncate Archive but when I use it, rsyslog can't write in database
db error (1062): Duplicate entry '202' for key 'PRIMARY' (log error).
To resolve the problem, I had to truncate syslog and archive_unparse table.
Truncate remove auto-increment and it's a probleme in the other table, i think it's prefereble to use 'DELETE FROM archive;' to purge this table.
Geckeon.

**Comment by proditis** [comment]
The reason we chose TRUNCATE instead of DELETE, is that delete needs special handling with transactions and transaction isolation. This becomes really problematic with blackhole/memory tables. 

However we need to figure out a safer way to achieve this cleanup. I will prepare an updated `protected/modules/syslog/controllers/ArchiveController.php` in hopes that it will solve this problem. 

Will let you know soon.

**Comment by proditis** [comment]
Just committed an updated version of  `ArchiveController.php`. Can you replace the file under `htdocs/protected/modules/syslog/controllers/ArchiveController.php` with the one at https://raw.githubusercontent.com/echothrust/echofish/master/htdocs/protected/modules/syslog/controllers/ArchiveController.php and see if this one fixes the problem?

**Comment by geckeon** [comment]
This fix resolve the TRUNCATE problem.
Thx for your reactivity.

**Comment by proditis** [comment]
Great news.

You're more than welcome :)

I'm closing this issue for now. If you experience any other issues with Echofish don't hesitate to open a new issue.

Pantelis

PS: We have a pending patch for the resolve hosts, we missed some edge-cases (it will be committed by this time tomorrow)
