### ISSUE TITLE
Manage Users

### ISSUE THREAD

**Issue by Koubiacz** [echothrust/echofish#45]
Hello,

I created a user who does not have administrative rights.

![user](https://cloud.githubusercontent.com/assets/5717132/17544325/c2fdbabc-5ed6-11e6-833c-946246278f19.PNG)
When I connect with this user, I can change other accounts and settings.

How to prevent this?

Thanks

**Comment by proditis** [comment]
Hi there Koubiacz,

At the moment all users of echofish are considered "administrators". 
These user options `superuser` & `level` are there so that we can avoid changing the SQL schema later on. 

We still haven't figured the right way to implement the actual controls. There are certain issues that we have a hard time deciding which way to go,  such as
* Do we allow non superusers to acknowledge logs?
* do we need to keep an audit trail of who acknowledged what?
* If we do keep an audit trail, how is best to make it usable for the superuser?
* Syslog module aside, how are non-superusers going to interact with the rest of the echofish modules (eg Lists, Statistics, etc)

Now to get back to the problem at hand, we can deny all access to the Settings module, so that non-superusers cant mess with it and its operations.  Will this be sufficient for your case or you had something else in mind? 


Pantelis

**Comment by Koubiacz** [comment]
Hello,

The solution of simply deny all access to the settings of modules is a good idea.
It shall prevent a user deletes all other accounts

**Comment by Koubiacz** [comment]
I changed the php files and the problem is solved

**Comment by proditis** [comment]
Thanks for testing this :) 

I will close this issue and finish up the modifications.

Pantelis
