### ISSUE TITLE
Abuser Triggers not working

### ISSUE THREAD

**Issue by bitroost** [echothrust/echofish#89]
First of all, i really like the concept of echofish. Hard to find anything similar that simple and lightweight.

I set up a Docker container using debian:8.10, mariadb 10.0.32, syslog-ng 3.5.6, nginx/php-fpm using supervisord and everything works fine except the Abuser Triggers.

- mariadb event_scheduler is ON,
- the Status for all events is ENABLED,
- Whitelisting works,
- Archives get truncated

the syslog-ng destination definition is
```
destination d_mysql {
        sql(
                type(mysql)
                host("127.0.0.1")
                username("echofish")
                password("***")
                database("ETS_echofish")
                table("archive_bh") 
                columns("host", "facility", "priority", "level", "program", "pid", "tag", "msg", "received_ts" )
                values("$HOST", "$FACILITY_NUM", "$PRIORITY","$LEVEL_NUM", "$PROGRAM", "$PID", "$TAG", "$MSG", "$YEAR-$MONTH-$DAY $HOUR:$MIN:$SEC" )
        );
};
```

Tried all kinds of trigger variants, even set msg to %, and pattern to /.+/, nothing gets triggered.

I am a bit lost now on how and where i should continue to test for mistakes/bugs/errors.

Besides that:

- In the "Create AbuserTrigger"-Form, Facility and Severity field-description mention wildcards but the form blocks that with a "must be a number"-Error.
- On the Logs-Page (Home/Syslog/Logs) if chosen to display "All" and then switching to Archive, especially with 7 days of Archive, the page hangs. I think Results display on the Archive page should not be able to display All, or at least reset from the Logs-Page.

**Comment by proditis** [comment]
Hello @bitroost thanks for taking the time to report these issues.

We will investigate and come back to you with further details on the issues you're having, in the mean time can you please provide:
* details on the message(s) you are trying to create the abuser trigger on, along with the details of the trigger you have created (capture, grouping etc)? 
* What version of echofish you working with?

In general the pattern needs to exactly match an IP address within the entire message. This is a PCRE pattern that you have to supply there in order to achieve that. 

In the background we perform a `REGEXP_REPLACE(msg, pattern, grouping)` where `grouping` is the backreferences to the subexpressions within the `pattern` in the form \N, where N is a number from 1 to 9. This should return only the IP address you're trying to match within `msg`.

Best regards,

Pantelis

**Comment by bitroost** [comment]
Hi @proditis, thanks for the quick reply.
This is a dump of what i set up but doesn't trigger ... 

```
INSERT INTO `abuser_trigger` VALUES 
(1,3,6,'proftpd','0.0.0.0 (%[%]) - FTP session %.','/\\[(.*?)\\]/',1,1,'proftpd login attempt',1,1,1),
(2,4,6,'sshd','Invalid user % from %','/from\\s(.+?)/',1,1,'sshd invalid user',1,1,1),
(3,2,4,'postfix/smtpd','warning: %[%]: SASL LOGIN authentication failed: authentication failure','/\\[(.*?)\\]/',1,1,'postfix/smtpd login failed',1,1,1);
```

And thats an excerpt from the syslog messages, as i understand they should all have been triggered:
```
Received Ts          Host        Facility  Level   Program        Msg
2018-04-11 15:46:17  172.17.0.1  authpriv  notice  proftpd        0.0.0.0 (212.2.155.16[212.2.155.16]) - USER www-data (Login failed): Incorrect password
```
```
Received Ts          Host        Facility  Level   Program  Msg
2018-04-11 14:35:07  172.17.0.1  auth      info    sshd     Invalid user oracle4 from 85.90.210.55	
2018-04-11 15:13:16  172.17.0.1  auth      info    sshd     Invalid user pi from 88.190.183.18	
2018-04-11 13:43:03  172.17.0.1  auth      info    sshd     Invalid user pi from 94.224.118.133	
```
```
Received Ts          Host        Facility  Level   Program        Msg
2018-04-11 14:35:27  172.17.0.1  mail      warn    postfix/smtpd  warning: 136-233-24-185.static.servebyte.com[185.24.233.136]: SASL LOGIN authentication failed: authentication failure	
2018-04-11 14:21:14  172.17.0.1  mail      warn    postfix/smtpd  warning: 136-233-24-185.static.servebyte.com[185.24.233.136]: SASL LOGIN authentication failed: authentication failure
2018-04-11 14:06:47  172.17.0.1  mail      warn    postfix/smtpd  warning: 136-233-24-185.static.servebyte.com[185.24.233.136]: SASL LOGIN authentication failed: authentication failure
```

I think i've done everything right, i thought already that the pattern has to match an IP exactly.
What's the Capture-field doing? I guess that's not used/obsolete?

Something else i thought about ... at what point are the triggers checked? Only as a new syslog message arrives or also when i add/update a trigger and on the existing syslog messages. Would be useful to know for testing.

**Comment by proditis** [comment]
Hi @bitroost thank you for the info.

It appears that our transition from mysql to mariadb left quite a mess behind, your issue really helps in clearing these out.

This is how your first trigger pattern should look like, from `/\\[(.*?)\\]/` => `^.*\\[(.*?)\\].*$`

In order to test your regexp you can perform the following simple tests from withing the mysql client
```mysql
SET @msg="0.0.0.0 (212.2.155.16[212.2.155.16]) - USER www-data (Login failed): Incorrect password";
SELECT REGEXP_REPLACE(@msg,'^.*\\[(.*?)\\].*$','\\1');
+------------------------------------------------+
| REGEXP_REPLACE(@msg,'^.*\\[(.*?)\\].*$','\\1') |
+------------------------------------------------+
| 212.2.155.16                                   |
+------------------------------------------------+
```
As a reference you can check out the official mariadb REGEXP_REPLACE documentation at https://mariadb.com/kb/en/library/regexp_replace/

The `Capture` field is there for backwards compatibility with the previous regexp library we used (`lib_mysqludf_preg`). This should be gone in the upcoming echofish version.

The triggers are checked after they have been inserted into the archive and they do not fire up when you update or replace them. However, you can force the trigger to fire on old messages by inserting the appropriate message ID from the archive entry to the table `archive_unparse`.  Assuming you have relatively small `archive` data set, something like this should force the updated trigger for proftpd to parse the messages again, flagging any abusers.
```
INSERT INTO `archive_unparse` SELECT `id`,1 FROM `archive` WHERE `facility`=3 and `priority`=6 
and `program`='proftpd' and `msg` like '0.0.0.0 (%[%]) - USER % (Login failed): Incorrect password'
```
If your archive is small enough you can also perform a re-parse of all the messages by 
`INSERT INTO archive_unparse SELECT id,1 FROM archive`.

Let me know if these work out for you.

**Comment by bitroost** [comment]
Hi @proditis,
i fixed the patterns of the triggers and they are working now!

So in a nutshell, on an echofish-installation using mariadb, the trigger-pattern needs to match the whole msg including a regex-group targeting the IP. Am i right?
